services:
  postgres-service:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"

  pgadmin-service:
    image: dpage/pgadmin4:9.6
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "88:80"
    depends_on:
      - postgres-service

  python-app:
    build: .
    image: python-app:1.0
    container_name: python_app
    env_file:
      - .env
    depends_on:
      - postgres-service
    volumes:
      - ./app:/app
